### PR TITLE
Change the input alignment for inputURI

### LINKED ISSUE #3319: Change Input alignment for inputURI
image

### PR DESCRIPTION
**Pull request by jcoyne**
## Why was this change made?

Fixes #3319

## How was this change tested?

Screen Shot 2021-11-12 at 2 37 34 PM

### CODE REVIEW

**Comment by justinlittman** [comment]
Can you shrink the property select (so that it stays consistent with the property select for other inputs)?
image

**Comment by jcoyne** [comment]
@justinlittman I didn't change the property select value. So I believe it's still consistent with how the other properties display.  If you shrink it, you wouldn't be able to read the property that is currently set.

**Comment by justinlittman** [comment]
It was changed from a `col-auto` to `col-sm-11`: https://github.com/LD4P/sinopia_editor/pull/3326/files#diff-b74052ea82c9b90e614e48590026aa71aba4cb3ad89618592b3379e38ee08d30R45

**Comment by jcoyne** [comment]
Yes, but col-auto allowed it to show the enirity of what was selected like this
Screen Shot 2021-11-13 at 8 34 01 AM

Cropping it down would make it more difficult to see what they had selected as the URL would get cropped.

**Comment by justinlittman** [comment]
I'm confused. It was previously `col-auto`, which allowed the select to resize as necessary. However, in this PR the select was changed to `col-sm-11`, which made it cover the width. The preference is for the select to be sized to the options, not cover the width.

**Comment by jcoyne** [comment]
Yes, the out of date mockups were causing confusion. I've made that auto now so it looks like this:
Screen Shot 2021-11-15 at 10 17 10 AM

**Review by justinlittman — APPROVED** [review]

**Pull request merged**
