### PR TITLE
Set the background color for the active editor menu

### LINKED ISSUE #2436: Background Color for Active Editor Nav
**Describe the feature you'd like**
Currently the active property in the left navigation has a blue background color:

Screen Shot 2020-09-08 at 11 47 10 AM

In the new design, the active property should either be a solid tan #D0C1A8 with black text if editing a RDF resource or a solid orange #B26F16 with white text if editing a resource template, 
image

### PR DESCRIPTION
**Pull request by jcoyne**
## Why was this change made?

Fixes #2436 
Screen Shot 2020-09-15 at 1 30 12 PM

### CODE REVIEW

**Review by jermnelson — CHANGES_REQUESTED** [review]
This isn't quite correct. The orange color (#B26F16 ) should only be set when editing a template, the default for editing resources should be  a solid tan #D0C1A8.

**Comment by jcoyne** [comment]
@jermnelson how do we know if it's a template or a resource?  Aren't they now in the same editor?

**Comment by aaron-collier** [comment]
Same question for https://github.com/LD4P/sinopia_editor/issues/2439

**Comment by jermnelson** [comment]
> @jermnelson how do we know if it's a template or a resource? Aren't they now in the same editor?

I think the easiest way would be to check the URL and see if it ends with `editor/sinopia:template:resource`, @justinlittman may know of a better option.

**Comment by jcoyne** [comment]
@jermnelson I don't think `findRootResourceTemplateId` is going to work because that requires you to provide a dataset (which I beleive is for importing RDF).

**Review by jermnelson — APPROVED** [review]

**Comment by jermnelson** [comment]
@jcoyne I think this can merged after a rebase.

**Comment by justinlittman** [comment]
Editing a resource template:
image

Editing a resource:
image

**Comment by justinlittman** [comment]
Pinging @jermnelson for a review at your convenience.

**Comment by jcoyne** [comment]
@justinlittman This needs a rebase now.  Would you be able to put the styles in https://github.com/LD4P/sinopia_editor/blob/master/src/styles/resourceNav.scss ?

**Comment by justinlittman** [comment]
Done @jcoyne

**Review by jermnelson — APPROVED** [review]

**Pull request merged**
