### PR TITLE
note version of node needed and reference package manager that c…

### PR DESCRIPTION
**Pull request by peetucket**
we think there was some discussion of node v12 not working?  if so, we should reference this in the readme

### CODE REVIEW

**Comment by ndushay** [comment]
i don't know if node 12 works or not, but we're configured in circleci and images to use node 10.11, i think, so I'm good with adding this to docs.  Can look at `circleci/config.yml` for more specific info.

Also ok with upgrading to newer node;  maybe make a ticket for that, too?

**Comment by peetucket** [comment]
created https://github.com/LD4P/sinopia_editor/issues/826

**Comment by jcoyne** [comment]
There's a typo in your commit message "pacakage"

**Comment by peetucket** [comment]
> There's a typo in your commit message "pacakage"

fixed and force pushed

**Pull request merged**
