### PR TITLE
Switch to using iso-639-2

### LINKED ISSUE #1230: change language choices for literals to ISO 639-2
**Describe the bug**
I am using the sinopia user feedback template in Windows/Firefox and I don't understand where the language choices are coming from and what appears to be a random order.  Not all the languages in the MARC list of languages appear to be there.  For example, when I enter Turkish I would expect to see Turkish as well as Ottoman Turkish, but I don't.

### PR DESCRIPTION
**Pull request by jcoyne**
Still need to see about how this handles old data.

Fixes #1230

### CODE REVIEW

**Comment by justinlittman** [comment]
Nice. A 1 character change required modifying 24 files ...

**Comment by justinlittman** [comment]
Sees to hang on ...
image

**Comment by jcoyne** [comment]
@justinlittman 60-70% is tests, which says something about the coupling of our tests and maybe about Redux (global state).

**Comment by jcoyne** [comment]
@justinlittman Ha! the iso639-2.json response uses iso-639-1 languages in the response:

Screen Shot 2019-11-18 at 8 06 16 AM

**Comment by justinlittman** [comment]
I thought tight coupling was the whole point of react/redux ...

**Pull request merged**
