### PR TITLE
Adds Tagged Release Checklist Github Issue Template

### PR DESCRIPTION
**Pull request by jermnelson**
Creates a checklist issue template for doing a tagged release.

### CODE REVIEW

**Comment by jcoyne** [comment]
If this is our only issue template, will it appear whenever we try to create a new issue?

**Comment by jermnelson** [comment]
> If this is our only issue template, will it appear whenever we try to create a new issue?
I believe you have to explicitly select the template to use it when creating a new issue; if this becomes bothersome, I would be happy to create other templates or remove this one.

**Comment by jcoyne** [comment]
@jermnelson Yep, this is now the only issue type:
Screen Shot 2019-07-17 at 9 53 18 PM

**Comment by jcoyne** [comment]
I guess there's the "Open a regular issue" link.

**Pull request merged**
