### PR TITLE
Replace the check on the left nav headings with a circle

### LINKED ISSUE #3100: Dot on the right indicates whether content has been entered for that field
image

### PR DESCRIPTION
**Pull request by jcoyne**
## Why was this change made?

Fixes #3100

## How was this change tested?

Screen Shot 2021-10-05 at 1 09 17 PM

### CODE REVIEW

**Review by ndushay — CHANGES_REQUESTED** [review]
don't we still want some kind of check for the new PresenceIndicator to show it's working right?

**Comment by jcoyne** [comment]
@ndushay I opted not to, because it's trivially simple.  If there's something in the array, the dot shows. 🤷

**Review by ndushay — CHANGES_REQUESTED** [review]
I like having the test - showing that the dot appears appropriately, AND that the dot disappears appropriately.  This is an important behavior in the UI.   Your implementation now is much better and simpler ... but keeping the test seems like a good idea -- it's also documenting the expected behavior of the app.

**Review by ndushay — APPROVED** [review]
I know how to do that sort of selector in ruby/capybara, but I haven't worked with cypress yet.  I'm gonna let it go.

**Pull request merged**
