### PR TITLE
Remove popper.

### LINKED ISSUE #2962: Upgrade popper
See https://www.npmjs.com/package/popper.js

### PR DESCRIPTION
**Pull request by justinlittman**
closes #2962

## Why was this change made?
Popper is a peer dependency of Bootstrap 4. With npm 7, peer dependencies are automatically installed, meaning that we no longer need to declare in `package.json`.

### CODE REVIEW

**Comment by ndushay** [comment]
oh no - failing tests

**Comment by justinlittman** [comment]
I think this is causing a problem with the type-ahead component. Try again after #2965

**Comment by jcoyne** [comment]
Isn't popperjs a dependency of Bootstrap?

**Comment by justinlittman** [comment]
@jcoyne See updated `Why was this change made?`

**Comment by jcoyne** [comment]
@justinlittman that reality doesn't seem to be reflected in the package-lock.json.

**Pull request merged**
