### PR TITLE
Allow selection of owning group and editing groups when saving. Upgra…

### LINKED ISSUE #2930: Update group choice modal
* Per new design
* User can select a group to be owner.
  * If user is a member of a single group, the group will be selected by default.
  * If user is a member of two or more groups, no groups will be selected by default.
* User can select zero more more editing groups:
  * This is from the list of all groups.

### LINKED ISSUE #2953: Upgrade @aws-amplify/auth
See https://www.npmjs.com/package/@aws-amplify/auth

### PR DESCRIPTION
**Pull request by justinlittman**
…des Ampify.

closes #2930

closes #2953

## Why was this change made?
So that the user can select permissions.

## How was this change tested?
Unit

## Which documentation and/or configurations were updated?
NA

### CODE REVIEW

**Comment by justinlittman** [comment]
image

**Comment by NancyL** [comment]
'Own" is a tricky word in this sphere--it suggests proprietary data with strings attached--though it's hard to find another term. Maybe "Who produced this?" "Who maintains this?" "What group is this in?" Not sure what should be emphasized. @michelleif any ideas?

**Review by ndushay — APPROVED** [review]
LGTM, modulo Nancy's concern about wording.

**Comment by justinlittman** [comment]
Wording can be updated later if necessary.

**Pull request merged**
