### PR TITLE
Add tls and net to the webpack node config so that request can be used

### PR DESCRIPTION
**Pull request by aaron-collier**
This is something I ran into while working on search and may be an issue elsewhere so pulling into a separate PR.

### CODE REVIEW

**Comment by jcoyne** [comment]
Can you explain more why we need this and how it fixes the problem?

**Comment by aaron-collier** [comment]
@jcoyne sure. I was seeing a lot of `Error: Cannot resolve module net` and `Error: Cannot resolve module tls` when using `request` in sinopiaServer (https://github.com/LD4P/sinopia_editor/pull/976/files#diff-66941f9cc553e538ea7a216facf360b6R188) in order to execute the search. I found this issue on request: https://github.com/request/request/issues/1529

Perhaps there is a better way to execute the query?

**Comment by aaron-collier** [comment]
@jcoyne it looks like I may be able to use `fetch` instead of `request` (as you did in the InputLookup), I'm happy to try that before this is merged to see if it can be avoided.

**Comment by aaron-collier** [comment]
Not having any luck with fetch, yet...

**Comment by jcoyne** [comment]
@aaron-collier request is a node module (for server side requests).  You wouldn't want to use that in client side code.  Maybe we should split the server into it's own repository (or directory at least)

**Comment by aaron-collier** [comment]
Ah... Ok, I think I've figured out how to query via parameter vs. form, so I think fetch will work and I can use the pattern you have in sinopialookup.

**Comment by aaron-collier** [comment]
Closing per discussion above.

**Pull request closed without merging**
